Repository bpetetot/conference-hall, pull requests merged in 2018-03, with the labels that each got.

#181 Use a batch to create organization
  src/firebase/organizations.js
  src/store/listeners/reactions/organizations.js
  src/store/reducers/data/index.js
Labels: :recycle: refactoring

#182 Display organization page
  src/components/avatar/avatarLabel.css
  src/components/avatar/avatarLabel.jsx
  src/components/list/listItem.css
  src/components/list/listItem.jsx
  src/firebase/organizations.js
  src/screens/components/speaker/speaker.container.js
  src/screens/organizer/organization/page/index.js
  src/screens/organizer/organization/page/organizationPage.container.js
  src/screens/organizer/organization/page/organizationPage.css
  src/screens/organizer/organization/page/organizationPage.jsx
  src/screens/organizer/organizations/organizations.container.js
  src/screens/organizer/organizer.jsx
  src/store/listeners/listeners.js
  src/store/listeners/reactions/organizations.js
  src/store/reducers/router/routes.js
Labels: :construction: WIP

#173 :white_check_mark: test shared components
  .circleci/config.yml
  package.json
  src/components/avatar/__snapshots__/avatar.spec.js.snap
  src/components/avatar/avatar.jsx
  src/components/avatar/avatar.spec.js
  src/components/badge/__snapshots__/badge.spec.js.snap
  src/components/badge/badge.spec.js
  src/components/copyInput/__snapshots__/copyInput.spec.js.snap
  src/components/copyInput/copyInput.jsx
  src/components/copyInput/copyInput.spec.js
  src/components/dropdown/__snapshots__/dropdown.spec.js.snap
  src/components/dropdown/dropdown.spec.js
  src/components/iconCard/iconCard.css
  src/components/iconCard/iconCard.jsx
  src/components/iconCard/index.js
  src/components/iconLabel/__snapshots__/iconLabel.spec.js.snap
  src/components/iconLabel/iconLabel.spec.js
  src/components/iconLink/__snapshots__/iconLink.spec.js.snap
  src/components/iconLink/iconLink.spec.js
  src/components/loader/__snapshots__/loader.spec.js.snap
  src/components/loader/loader.spec.js
  src/components/maps/__snapshots__/maps.spec.js.snap
  src/components/maps/maps.spec.js
  src/components/markdown/__snapshots__/markdown.spec.js.snap
  src/components/markdown/markdown.spec.js
  src/components/navbar/__snapshots__/navbar.spec.js.snap
  src/components/navbar/navbar.spec.js
  src/components/relativeDate/__snapshots__/relativeDate.spec.js.snap
  src/components/relativeDate/relativeDate.spec.js
  src/components/titlebar/__snapshots__/titlebar.spec.js.snap
  src/components/titlebar/titlebar.spec.js
  src/setupTests.js
  src/tests/snapshot.jsx
  yarn.lock
Labels: :construction: WIP

#186 Talk submission from My talks
  src/firebase/events.js
  src/screens/components/talk/index.js
  src/screens/components/talk/submissions/submissions.css
  src/screens/components/talk/submissions/submissions.jsx
  src/screens/components/talk/title/index.js
  src/screens/components/talk/title/title.css
  src/screens/components/talk/title/title.jsx
  src/screens/speaker/components/noEvents/index.js
  src/screens/speaker/components/noEvents/noEvents.jsx
  src/screens/speaker/event/submission/submission.container.js
  src/screens/speaker/speaker.jsx
  src/screens/speaker/talk/submission/eventsSelection/eventsSelection.container.js
  src/screens/speaker/talk/submission/eventsSelection/eventsSelection.jsx
  src/screens/speaker/talk/submission/eventsSelection/index.js
  src/screens/speaker/talk/submission/index.js
  src/screens/speaker/talk/submission/submission.container.js
  src/screens/speaker/talk/submission/submission.css
  src/screens/speaker/talk/submission/submission.jsx
  src/store/listeners/listeners.js
  src/store/listeners/reactions/events.js
  src/store/reducers/data/events.selector.js
  src/store/reducers/data/index.js
  src/store/reducers/router/routes.js
  src/store/reducers/ui/speaker/index.js
  src/store/reducers/ui/speaker/myEvents.js
  src/store/reducers/ui/speaker/myEvents.selector.js
Labels: :sparkles: feature

#189 :sparkles: contributors page
  .env
  package.json
  src/components/iconLink/__snapshots__/iconLink.spec.js.snap
  src/components/iconLink/iconLink.jsx
  src/helpers/github.js
  src/screens/components/contributors/contributor.css
  src/screens/components/contributors/contributor.jsx
  src/screens/components/contributors/contributors.css
  src/screens/components/contributors/contributors.jsx
  src/screens/components/contributors/index.js
  src/screens/components/navbar/avatarDropdown/avatarDropdown.container.js
  src/screens/components/navbar/avatarDropdown/avatarDropdown.jsx
  src/screens/components/navbar/navbar.jsx
  src/screens/organizer/organizer.jsx
  src/screens/organizer/proposal/speakers/speaker/speaker.jsx
  src/screens/speaker/speaker.jsx
  src/store/reducers/router/routes.js
Labels: :construction: WIP, :sparkles: feature

#163 :recycle: use of driver redux-little-router
  package.json
  src/screens/components/brand/brand.container.js
  src/screens/components/brand/brandMobile/brandMobile.container.js
  src/screens/components/event/event.container.js
  src/screens/components/navbar/avatarDropdown/avatarDropdown.container.js
  src/screens/components/notFound/notFound.container.js
  src/screens/components/talk/speakers/addSpeaker/inviteSpeaker/inviteSpeaker.container.js
  src/screens/components/talk/speakers/addSpeaker/speakerResults/speakerResults.container.js
  src/screens/components/talk/speakers/removeSpeaker/removeSpeaker.container.js
  src/screens/components/talk/submissions/submission/submission.container.js
  src/screens/organizer/event/edit/eventEdit.container.js
  src/screens/organizer/events/events.container.js
  src/screens/organizer/proposal/proposal.container.js
  src/screens/organizer/proposals/proposalFilters/proposalFilters.container.js
  src/screens/organizer/proposals/proposals.container.js
  src/screens/organizer/sidebar/event/eventSidebar.container.js
  src/screens/speaker/event/submission/submission.container.js
  src/screens/speaker/inviteSpeaker/inviteSpeaker.container.js
  src/screens/speaker/myTalks/myTalks.container.js
  src/screens/speaker/talk/edit/talkEdit.container.js
  src/screens/speaker/talk/page/submission/submission.container.js
  src/screens/speaker/talk/page/talkPage.container.js
  src/screens/speaker/talk/submission/submission.container.js
  src/store/drivers/index.js
  src/store/drivers/redux-little-router/index.js
  src/store/drivers/redux-little-router/router.selectors.js
  src/store/drivers/redux-little-router/routes.js
  src/store/drivers/reduxForm.js
  src/store/listeners/reactions/app.js
  src/store/listeners/reactions/auth.js
  src/store/listeners/reactions/events.js
  src/store/listeners/reactions/proposals.js
  src/store/listeners/reactions/ratings.js
  src/store/listeners/reactions/router.js
  src/store/listeners/reactions/submissions.js
  src/store/listeners/reactions/talks.js
  src/store/reducers/auth/protect.js
  src/store/reducers/reducers.js
  src/store/reducers/router/index.js
  src/store/store.js
  src/styles/themes/withTheme.js
  yarn.lock
Labels: :construction: WIP, :wrench: technical

#192 :sparkles: delete a talk
  src/components/form/inputButton/inputButton.jsx
  src/components/modal/modal.jsx
  src/firebase/crud.js
  src/screens/speaker/talk/page/delete/deleteTalk.jsx
  src/screens/speaker/talk/page/delete/deleteTalkModal.container.js
  src/screens/speaker/talk/page/delete/deleteTalkModal.css
  src/screens/speaker/talk/page/delete/deleteTalkModal.jsx
  src/screens/speaker/talk/page/delete/index.js
  src/screens/speaker/talk/page/talkPage.jsx
  src/store/listeners/listeners.js
  src/store/listeners/reactions/talks.js
  src/store/reducers/data/talks.selector.js
Labels: :sparkles: feature

#195 :arrow_up: upgrade dependencies
  package.json
  yarn.lock
Labels: :wrench: technical

#197 :sparkles: speaker survey (#169)
  src/components/form/checkbox/checkbox.css
  src/components/form/checkbox/checkbox.jsx
  src/components/form/checkbox/index.js
  src/components/form/index.js
  src/components/form/renderCheckbox.jsx
  src/firebase/survey.js
  src/screens/components/event/event.css
  src/screens/components/event/event.jsx
  src/screens/components/event/eventTitle/eventTitle.css
  src/screens/components/event/eventTitle/eventTitle.jsx
  src/screens/components/event/survey/form/index.js
  src/screens/components/event/survey/form/surveyForm.container.js
  src/screens/components/event/survey/form/surveyForm.jsx
  src/screens/components/event/survey/form/surveyInput/index.js
  src/screens/components/event/survey/form/surveyInput/surveyInput.css
  src/screens/components/event/survey/form/surveyInput/surveyInput.jsx
  src/screens/components/event/survey/questions.js
  src/screens/organizer/event/edit/eventEdit.jsx
  src/screens/organizer/event/edit/eventTabs/eventTabs.css
  src/screens/organizer/event/edit/eventTabs/eventTabs.jsx
  src/screens/organizer/event/edit/survey/index.js
  src/screens/organizer/event/edit/survey/survey.container.js
  src/screens/organizer/event/edit/survey/survey.css
  src/screens/organizer/event/edit/survey/survey.jsx
  src/screens/speaker/event/submission/submission.jsx
  src/screens/speaker/event/survey/index.js
  src/screens/speaker/event/survey/survey.container.js
  src/screens/speaker/event/survey/survey.css
  src/screens/speaker/event/survey/survey.jsx
  src/screens/speaker/sidebar/event/eventSidebar.container.js
  src/screens/speaker/sidebar/event/eventSidebar.jsx
  src/screens/speaker/speaker.jsx
  src/store/drivers/redux-little-router/routes.js
  src/store/listeners/listeners.js
  src/store/listeners/reactions/router.js
  src/store/listeners/reactions/survey.js
  src/store/reducers/data/index.js
  src/styles/components/input.css
Labels: :sparkles: feature

#205 :sparkles: add event contact email
  src/screens/components/event/contactBlock/contactBlock.jsx
  src/screens/components/event/contactBlock/index.js
  src/screens/components/event/event.jsx
  src/screens/organizer/event/components/eventForm/eventForm.jsx
  src/styles/components/input.css
Labels: :fire: enhancement
