Repository bpetetot/conference-hall, pull requests merged in 2018-04, with the labels that each got.

#184 Add member in organization
  package.json
  src/components/addUser/addUserButton.css
  src/components/addUser/addUserButton.jsx
  src/components/addUser/addUserModal.container.js
  src/components/addUser/addUserModal.css
  src/components/addUser/addUserModal.jsx
  src/components/addUser/index.js
  src/components/addUser/userResults/index.js
  src/components/addUser/userResults/userResults.css
  src/components/addUser/userResults/userResults.jsx
  src/components/modal/withModal.js
  src/screens/components/talk/speakers/addSpeaker/addSpeakerButton.container.js
  src/screens/components/talk/speakers/addSpeaker/addSpeakerButton.jsx
  src/screens/components/talk/speakers/addSpeaker/addSpeakerModal.container.js
  src/screens/components/talk/speakers/addSpeaker/addSpeakerModal.css
  src/screens/components/talk/speakers/addSpeaker/addSpeakerModal.jsx
  src/screens/components/talk/speakers/addSpeaker/index.js
  src/screens/components/talk/speakers/addSpeaker/inviteSpeaker/index.js
  src/screens/components/talk/speakers/addSpeaker/inviteSpeaker/inviteSpeaker.container.js
  src/screens/components/talk/speakers/addSpeaker/speakerResults/index.js
  src/screens/components/talk/speakers/addSpeaker/speakerResults/speakerResults.jsx
  src/screens/organizer/inviteOrganizer/index.js
  src/screens/organizer/inviteOrganizer/inviteOrganizer.container.js
  src/screens/organizer/inviteOrganizer/inviteOrganizer.css
  src/screens/organizer/inviteOrganizer/inviteOrganizer.jsx
  src/screens/organizer/organization/page/organizationPage.container.js
  src/screens/organizer/organization/page/organizationPage.jsx
  src/screens/organizer/organizer.jsx
  src/store/drivers/redux-little-router/routes.js
  src/store/listeners/listeners.js
  src/store/listeners/reactions/talks.js
  src/store/listeners/reactions/user.js
  src/store/reducers/ui/index.js
  src/store/reducers/ui/speaker/index.js
  src/store/reducers/ui/userAddModal.js
Labels: :sparkles: feature

#207 Link an organization to an event
  src/components/form/index.js
  src/components/form/renderField.jsx
  src/screens/organizer/event/components/eventForm/eventForm.jsx
  src/screens/organizer/event/create/eventCreate.container.js
  src/screens/organizer/event/edit/eventForm/eventEdit.container.js
Labels: :sparkles: feature

#209 Remove member from organization
  src/components/list/listItem.jsx
  src/screens/organizer/organization/components/memberRow/index.js
  src/screens/organizer/organization/components/memberRow/memberRow.css
  src/screens/organizer/organization/components/memberRow/memberRow.jsx
  src/screens/organizer/organization/page/organizationPage.container.js
  src/screens/organizer/organization/page/organizationPage.jsx
Labels: :sparkles: feature

#208 Aggregate organization events
  src/firebase/organizations.js
  src/store/listeners/reactions/events.js
Labels: :sparkles: feature

#210 Leave organization
  src/screens/organizer/organization/components/memberRow/memberRow.jsx
  src/screens/organizer/organization/page/organizationPage.container.js
  src/screens/organizer/organization/page/organizationPage.jsx
  src/store/listeners/reactions/user.js
Labels: :sparkles: feature

#211 Rename organization
  src/screens/organizer/organization/edit/index.js
  src/screens/organizer/organization/edit/organizationEdit.container.js
  src/screens/organizer/organization/page/organizationPage.jsx
  src/screens/organizer/organizer.jsx
  src/store/drivers/redux-little-router/routes.js
  src/store/listeners/listeners.js
  src/store/listeners/reactions/organizations.js
Labels: :sparkles: feature

#213 :bug: fix some bugs with organizations
  src/components/addUser/addUserButton.jsx
  src/screens/organizer/inviteOrganizer/inviteOrganizer.container.js
  src/screens/organizer/inviteOrganizer/inviteOrganizer.jsx
  src/store/listeners/reactions/organizations.js
  src/store/listeners/reactions/user.js
Labels: :bug: bug

#196 retain filters on the proposal route
  src/store/listeners/reactions/proposals.js
Labels: :fire: enhancement

#216 :sparkles: restrict "organizer hall" with beta-invite access
  README.md
  src/components/form/inputButton/inputButton.css
  src/firebase/betaAccess.js
  src/screens/conference/betaAccess/betaAccess.container.js
  src/screens/conference/betaAccess/betaAccess.css
  src/screens/conference/betaAccess/betaAccess.jsx
  src/screens/conference/betaAccess/betaAccess.listeners.js
  src/screens/conference/betaAccess/hoc/index.js
  src/screens/conference/betaAccess/hoc/restrict.js
  src/screens/conference/betaAccess/index.js
  src/screens/conference/conference.jsx
  src/screens/organizer/organizer.jsx
  src/store/drivers/redux-little-router/routes.js
  src/store/reducers/ui/beta.js
  src/store/reducers/ui/index.js
Labels: :sparkles: feature

#221 :boom: change organizer db structure
  src/firebase/organizations.js
  src/screens/conference/betaAccess/hoc/restrict.js
  src/screens/organizer/event/create/eventCreate.container.js
  src/screens/organizer/event/edit/eventForm/eventEdit.container.js
  src/screens/organizer/inviteOrganizer/inviteOrganizer.container.js
  src/screens/organizer/organization/components/memberRow/index.js
  src/screens/organizer/organization/components/memberRow/memberRow.container.js
  src/screens/organizer/organization/components/memberRow/memberRow.jsx
  src/screens/organizer/organization/page/organizationPage.container.js
  src/screens/organizer/organization/page/organizationPage.jsx
  src/screens/organizer/organizations/organizations.container.js
  src/store/listeners/listeners.js
  src/store/listeners/reactions/auth.js
  src/store/listeners/reactions/events.js
  src/store/listeners/reactions/organizations.js
  src/store/listeners/reactions/user.js
  src/store/reducers/auth/protect.js
Labels: :recycle: refactoring

#159 :lock: security rules
  config/firestore.rules
  src/firebase/user.js
Labels: :wrench: technical

#222 :lipstick: some UI and UX
  src/components/form/inputButton/inputButton.css
  src/screens/organizer/event/components/eventForm/eventForm.jsx
  src/screens/speaker/event/submission/talkSubmitted/talkSubmitted.jsx
Labels: :lipstick: styles

#224 :arrow_up: upgrade dependencies
  package.json
  yarn.lock
Labels: :wrench: technical

#225 :sparkles: add not rated proposals filter
  src/firebase/proposals.js
  src/screens/organizer/proposals/proposalFilters/proposalFilters.container.js
  src/screens/organizer/proposals/proposalFilters/proposalFilters.jsx
  src/store/drivers/redux-little-router/routes.js
  src/store/listeners/reactions/router.js
Labels: :sparkles: feature

#227 :sparkles: :bug: quick fixes and enhancements
  src/screens/components/event/survey/questions.js
  src/screens/speaker/event/submission/talkSubmitted/index.js
  src/screens/speaker/event/submission/talkSubmitted/talkSubmitted.container.js
  src/screens/speaker/event/submission/talkSubmitted/talkSubmitted.css
  src/screens/speaker/event/submission/talkSubmitted/talkSubmitted.jsx
  src/screens/speaker/talk/components/talkForm/talkForm.jsx
Labels: :bug: bug, :sparkles: feature

#228 :sparkles: send email after submission
  .gitignore
  README.md
  firebase.json
  functions/README.md
  functions/email.js
  functions/index.js
  functions/package.json
  functions/templates/talkConfirmed.js
  functions/yarn.lock
Labels: :sparkles: feature
