Repository bpetetot/conference-hall, pull requests merged in 2019-06, with the labels that each got.

#576 :arrow_up: upgrade minor/patched dependencies
  functions/package.json
  functions/yarn.lock
  package.json
  yarn.lock
Labels: :wrench: technical

#577 :arrow_up: upgrade react final form and sizes
  .circleci/config.yml
  .nvmrc
  docs/app/installation.mdx
  functions/.nvmrc
  functions/package.json
  package.json
  scripts/.nvmrc
  src/components/form/field/__snapshots__/field.spec.jsx.snap
  src/components/form/renderField.jsx
  yarn.lock
Labels: :wrench: technical

#578 :arrow_up: upgrade docz
  CHANGELOG.md
  docs/app/changelog.mdx
  doczrc.js
  package.json
  src/components/avatar/avatar.mdx
  src/components/badge/badge.mdx
  src/components/button/button.mdx
  src/components/form/toggle/toggle.mdx
  src/components/portals/confirmation/confirmation.mdx
  src/components/portals/drawer/drawer.mdx
  src/components/portals/modal/modal.mdx
  src/components/snackbar/snackbar.mdx
  src/components/thread/threads.mdx
  yarn.lock
Labels: :wrench: technical

#579 :arrow_up: upgrade firebase-admin, path-to-regex, nyc
  functions/package.json
  functions/yarn.lock
  package.json
  scripts/package.json
  scripts/yarn.lock
  yarn.lock
Labels: dependencies

#580 :arrow_up: upgrade react-script
  .env
  README.md
  jsconfig.json
  package.json
  src/components/form/dayPicker/index.js
  src/components/list/__snapshots__/listItem.spec.jsx.snap
  yarn.lock
Labels: dependencies

#559 :sparkles: revisit proposal page to decouple deliberation from email s…
  docs/app/installation.mdx
  functions/email/emailWebhooks.js
  functions/email/emailWebhooks.test.js
  functions/email/index.js
  functions/firestore/proposal.js
  functions/index.js
  functions/triggers/onUpdateProposal.js
  functions/triggers/onUpdateProposal.test.js
  src/components/dropdown/dropdown.css
  src/components/dropdown/dropdown.jsx
  src/components/form/checkbox/checkbox.jsx
  src/components/list/__snapshots__/listItem.spec.jsx.snap
  src/components/list/listItem.css
  src/components/list/listItem.jsx
  src/layout/avatarDropdown/avatarDropdown.jsx
  src/screens/organizer/components/talkSelection/talkSelection.container.js
  src/screens/organizer/components/talkSelection/talkSelection.jsx
  src/screens/organizer/proposals/proposals.container.js
  src/screens/organizer/proposals/proposals.jsx
  src/screens/organizer/proposals/proposals.listeners.js
  src/screens/organizer/proposals/proposals.reactions.js
  src/screens/organizer/proposals/proposalsList/proposalInfo/proposalInfo.css
  src/screens/organizer/proposals/proposalsList/proposalsList.container.js
  src/screens/organizer/proposals/proposalsList/proposalsList.jsx
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.container.js
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.jsx
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.module.css
  src/store/reducers/ui/organizer/index.js
  src/store/reducers/ui/organizer/proposalsSelection.js
Labels: :sparkles: feature

#585 :green_heart: use node 8 in all circle ci images
  .circleci/config.yml
Labels: :wrench: technical

#586 :bug: loading infinite after event creation
  package.json
  src/store/reactions/events.js
  yarn.lock
Labels: :bug: bug
