Repository bpetetot/conference-hall, pull requests merged in 2019-12, with the labels that each got.

#728 :arrow_up: upgrade dependencies
  functions/package.json
  functions/yarn.lock
  package.json
  yarn.lock
Labels: :wrench: technical

#733 :arrow_up: upgrade dependencies
  package.json
  yarn.lock
Labels: :wrench: technical

#734 :sparkles: add donate link in sidebar
  src/layout/sidebar/sidebar.css
  src/layout/sidebar/sidebar.jsx
Labels: :sparkles: feature

#735 :bug: clear local storage when signed out
  src/store/reactions/auth.js
Labels: :bug: bug

#737 :sparkles: edit a proposal as organizer
  src/components/portals/modal/modal.css
  src/screens/organizer/proposal/actions/actions.jsx
  src/screens/organizer/proposal/actions/editProposal/edit.jsx
  src/screens/organizer/proposal/actions/editProposal/edit.module.css
  src/screens/organizer/proposal/actions/editProposal/form/form.container.js
  src/screens/organizer/proposal/actions/editProposal/form/form.jsx
  src/screens/organizer/proposal/actions/editProposal/form/form.module.css
  src/screens/organizer/proposal/actions/editProposal/form/index.js
  src/screens/organizer/proposal/actions/editProposal/index.js
  src/screens/organizer/proposal/proposal.jsx
Labels: :sparkles: feature

#741 :construction_worker: setup github actions
  .circleci/config.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  package.json
Labels: :construction: WIP, :wrench: technical

#743 :bug: fix a bug avoiding event page reload
  src/store/reactions/app.js
Labels: :bug: bug

#742 :sparkles: managing organizer roles
  config/firestore.rules
  config/firestore.rules.spec.js
  functions/__mocks__/firebase-admin.js
  functions/direct/invite.js
  functions/direct/invite.spec.emul.js
  functions/direct/organization.js
  functions/direct/organization.spec.emul.js
  functions/index.js
  scripts/helpers/updates.js
  scripts/update-event-new-settings.js
  scripts/update-organization-roles.js
  src/components/avatar/__snapshots__/avatar.spec.jsx.snap
  src/components/avatar/avatar.jsx
  src/components/thread/__snapshots__/thread.spec.jsx.snap
  src/firebase/constants.js
  src/firebase/organizations.js
  src/firebase/user.js
  src/screens/components/addUserModal/addUserModal.jsx
  src/screens/components/hasRole/hasRole.container.js
  src/screens/components/hasRole/hasRole.jsx
  src/screens/components/hasRole/index.js
  src/screens/organizer/components/talkSelection/talkSelection.container.js
  src/screens/organizer/components/talkSelection/talkSelection.jsx
  src/screens/organizer/event/edit/eventEdit.jsx
  src/screens/organizer/organization/page/addMember/addMember.jsx
  src/screens/organizer/organization/page/changeRole/changeRole.container.js
  src/screens/organizer/organization/page/changeRole/changeRole.jsx
  src/screens/organizer/organization/page/changeRole/index.js
  src/screens/organizer/organization/page/changeRole/roleText.jsx
  src/screens/organizer/organization/page/memberRow/memberRow.container.js
  src/screens/organizer/organization/page/memberRow/memberRow.css
  src/screens/organizer/organization/page/memberRow/memberRow.jsx
  src/screens/organizer/organization/page/memberRow/memberRow.module.css
  src/screens/organizer/organization/page/organizationPage.container.js
  src/screens/organizer/organization/page/organizationPage.jsx
  src/screens/organizer/organization/page/removeMember/index.js
  src/screens/organizer/organization/page/removeMember/removeMember.container.js
  src/screens/organizer/organization/page/removeMember/removeMember.jsx
  src/screens/organizer/organization/page/removeMember/useLeaveOrganization.js
  src/screens/organizer/proposal/actions/actions.jsx
  src/screens/organizer/proposals/proposals.jsx
  src/screens/organizer/proposals/proposalsFilters/proposalsFilters.container.js
  src/screens/organizer/proposals/proposalsFilters/proposalsFilters.jsx
  src/screens/organizer/proposals/proposalsList/proposalSubtitle/proposalSubtitle.container.js
  src/screens/organizer/proposals/proposalsList/proposalsList.container.js
  src/screens/organizer/proposals/proposalsList/proposalsList.jsx
  src/screens/organizer/sidebar/event/eventSidebar.jsx
  src/store/listeners.js
  src/store/reactions/auth.js
  src/store/reactions/organizations.js
Labels: :sparkles: feature

#744 :sparkles: add link to request beta key
  src/screens/conference/betaAccess/betaAccess.jsx
  src/screens/conference/betaAccess/betaAccess.module.css
Labels: :wrench: technical

#745 :sparkles: add photo url in profile form
  package.json
  src/components/form/validators.js
  src/components/form/validators.spec.js
  src/screens/components/profile/profile.container.js
  src/screens/components/profile/profile.css
  src/screens/components/profile/profile.jsx
  src/store/reactions/auth.js
  yarn.lock
Labels: :bug: bug

#685 Add and delete a talk from a meetup
  config/firestore.rules
  src/components/calendar/monthCalendar/monthCalendar.css
  src/components/calendar/monthCalendar/monthCalendar.jsx
  src/components/calendar/monthCalendar/monthCalendar.story.mdx
  src/components/calendar/monthCalendar/navigator/index.js
  src/components/calendar/monthCalendar/navigator/navigator.jsx
  src/components/calendar/monthCalendar/navigator/navigator.module.css
  src/components/helpers/openTrigger/openTrigger.jsx
  src/components/portals/drawer/drawer.jsx
  src/firebase/meetups.js
  src/screens/organizer/agenda/agenda.jsx
  src/screens/organizer/agenda/createMeetup/createMeetup.jsx
  src/screens/organizer/agenda/createMeetup/index.js
  src/screens/organizer/agenda/editMeetup/editMeetup.jsx
  src/screens/organizer/agenda/editMeetup/index.js
  src/screens/organizer/meetup/form/meetupCreate.container.js
  src/screens/organizer/meetup/form/meetupEdit.container.js
  src/screens/organizer/meetup/form/meetupForm.jsx
  src/screens/organizer/meetup/form/meetupForm.module.css
  src/store/reactions/agenda.js
  src/store/reactions/meetups.js
Labels: :sparkles: feature
