Repository bpetetot/conference-hall, pull requests merged in 2019-07, with the labels that each got.

#600 :arrow_up: upgrade dependencies
  functions/.nvmrc
  functions/package.json
  functions/yarn.lock
  package.json
  scripts/package.json
  scripts/yarn.lock
  yarn.lock
Labels: :wrench: technical

#589 :sparkles: customize your event with a banner
  .env
  config/storage.rules
  docs/app/installation.mdx
  src/components/copyInput/copyInput.jsx
  src/layout/layout.css
  src/layout/layout.jsx
  src/screens/components/event/banner/banner.container.js
  src/screens/components/event/banner/banner.jsx
  src/screens/components/event/banner/banner.module.css
  src/screens/components/event/banner/images/default.jpg
  src/screens/components/event/banner/index.js
  src/screens/components/event/cfpBlock/cfpBlock.css
  src/screens/components/event/cfpBlock/cfpBlock.jsx
  src/screens/components/event/event.css
  src/screens/components/event/event.jsx
  src/screens/components/event/eventActions/eventActions.css
  src/screens/components/event/eventActions/eventActions.jsx
  src/screens/components/event/eventActions/index.js
  src/screens/organizer/event/edit/customize/customize.container.js
  src/screens/organizer/event/edit/customize/customize.jsx
  src/screens/organizer/event/edit/customize/customize.module.css
  src/screens/organizer/event/edit/customize/index.js
  src/screens/organizer/event/edit/eventEdit.jsx
  src/screens/organizer/event/edit/eventTabs/eventTabs.jsx
  src/store/listeners.js
  src/store/reactions/firebase.js
  src/store/routes.js
Labels: :sparkles: feature

#610 :arrow_up: upgrade dependencies lodash, firebase, final-form
  functions/package.json
  functions/yarn.lock
  package.json
  scripts/package.json
  scripts/yarn.lock
  yarn.lock
Labels: dependencies

#611 :sparkles: add tooltip for the message to organizers
  src/screens/speaker/event/submitWizard/talkSubmission/talkSubmission.jsx
Labels: :sparkles: feature

#612 :sparkles: add status and date to proposal page
  src/helpers/firebase.js
  src/screens/organizer/components/talkSelection/talkSelection.jsx
  src/screens/organizer/components/talkSelection/talkSelection.module.css
  src/screens/organizer/proposal/proposal.container.js
  src/screens/organizer/proposal/proposal.jsx
  src/screens/organizer/proposal/talk/talk.css
  src/screens/organizer/proposal/talk/talk.jsx
  src/screens/organizer/proposal/talk/talk.module.css
Labels: :fire: enhancement

#618 :bug: fix timezone issues and date formats
  functions/direct/submission.js
  package.json
  src/components/form/address/address.jsx
  src/components/form/validators.js
  src/components/form/validators.spec.js
  src/helpers/date.js
  src/helpers/firebase.js
  src/screens/components/event/cfpBlock/cfpBlock.container.js
  src/screens/components/event/cfpBlock/cfpBlock.css
  src/screens/components/event/cfpBlock/cfpBlock.jsx
  src/screens/components/eventDates/eventDates.jsx
  src/screens/organizer/event/form/eventForm.jsx
  src/screens/organizer/events/events.jsx
  src/screens/organizer/proposal/talk/talk.jsx
  src/screens/speaker/talk/submission/eventsSelection/eventsSelection.jsx
  src/store/reducers/data/events.selector.js
  yarn.lock
Labels: :bug: bug

#619 :arrow_up: upgrade dependencies
  functions/package.json
  functions/yarn.lock
  package.json
  scripts/package.json
  scripts/yarn.lock
  yarn.lock
Labels: dependencies

#621 :see_no_evil: add vscode settings folder in gitignore
  .gitignore
Labels: :wrench: technical

#622 :bug: fix infinite loading on organizer invite redirections
  src/store/reactions/router.js
Labels: :bug: bug

#623 :bug: fix update of name and photo of the user when signed-in
  src/store/reactions/auth.js
Labels: :bug: bug

#624 ✨ ratings progress indicator
  src/components/button/button.css
  src/components/dropdown/dropdown.css
  src/components/list/listItem.css
  src/components/list/listItem.jsx
  src/screens/organizer/components/ratingsProgress/index.js
  src/screens/organizer/components/ratingsProgress/ratingsProgress.container.js
  src/screens/organizer/components/ratingsProgress/ratingsProgress.jsx
  src/screens/organizer/components/ratingsProgress/ratingsProgress.module.css
  src/screens/organizer/events/events.container.js
  src/screens/organizer/proposals/proposals.container.js
  src/screens/organizer/proposals/proposals.jsx
  src/screens/organizer/proposals/proposalsFilters/index.js
  src/screens/organizer/proposals/proposalsFilters/proposalsFilters.container.js
  src/screens/organizer/proposals/proposalsFilters/proposalsFilters.jsx
  src/screens/organizer/proposals/proposalsFilters/proposalsFilters.module.css
  src/screens/organizer/proposals/proposalsHeader/index.js
  src/screens/organizer/proposals/proposalsHeader/proposalsHeader.jsx
  src/screens/organizer/proposals/proposalsHeader/proposalsHeader.module.css
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.container.js
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.jsx
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.module.css
  src/store/listeners.js
  src/store/reactions/events.js
  src/store/reducers/data/ratings.selectors.js
  src/store/reducers/ui/organizer/proposalsSelection.js
Labels: :sparkles: feature

#628 ✨ export card proposals in PDF
  functions/api/index.js
  functions/api/private/exportEvent.js
  functions/api/private/pdfCards/card.template.js
  functions/api/private/pdfCards/cards.template.js
  functions/api/private/pdfCards/index.js
  functions/package.json
  functions/yarn.lock
  src/components/alert/__snapshots__/alert.spec.jsx.snap
  src/components/button/button.css
  src/components/button/button.jsx
  src/components/button/button.mdx
  src/components/dropdown/dropdown.css
  src/components/portals/confirmation/__snapshots__/confirmation.spec.jsx.snap
  src/components/thread/__snapshots__/thread.spec.jsx.snap
  src/screens/organizer/proposals/proposalsList/proposalsList.container.js
  src/screens/organizer/proposals/proposalsList/proposalsList.jsx
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.container.js
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.jsx
  src/store/reactions/proposals.js
  src/store/reducers/ui/organizer/proposalsExport.js
Labels: :sparkles: feature

#629 :card_file_box: new firestore indexes format
  config/firestore.indexes.json
Labels: :wrench: technical

#630 🐛 reset paging reloading proposals
  src/screens/organizer/proposals/proposals.jsx
  src/screens/organizer/proposals/proposals.reactions.js
  src/screens/organizer/proposals/proposalsCards/card/card.container.js
  src/screens/organizer/proposals/proposalsCards/card/card.css
  src/screens/organizer/proposals/proposalsCards/card/card.jsx
  src/screens/organizer/proposals/proposalsCards/card/index.js
  src/screens/organizer/proposals/proposalsCards/card/surveyInfo/index.js
  src/screens/organizer/proposals/proposalsCards/card/surveyInfo/surveyInfo.container.js
  src/screens/organizer/proposals/proposalsCards/card/surveyInfo/surveyInfo.jsx
  src/screens/organizer/proposals/proposalsCards/index.js
  src/screens/organizer/proposals/proposalsCards/proposalsExport.container.js
  src/screens/organizer/proposals/proposalsCards/proposalsExport.css
  src/screens/organizer/proposals/proposalsCards/proposalsExport.jsx
Labels: :bug: bug

#632 :sparkles: update the fullname in the profile
  src/screens/components/profile/profile.jsx
  src/screens/speaker/event/submitWizard/talkSubmission/talkSubmission.css
  src/store/reactions/auth.js
Labels: :sparkles: feature

#571 :sparkles: rsvp.action.email.confirmation
  docs/app/installation.mdx
  docs/app/one-click_confirmation.gif
  functions/email/rsvp.js
  functions/email/templates/talkAccepted.js
  functions/email/templates/talkConfirmed.js
  functions/email/templates/talkDeclined.js
  functions/email/templates/talkReceived.js
  functions/email/templates/talkRejected.js
  functions/email/templates/talkSubmitted.js
  functions/firestore/proposal.js
  functions/triggers/onCreateProposal.js
  functions/triggers/onUpdateProposal.js
  functions/triggers/onUpdateProposal.test.js
  functions/triggers/onUpdateTalk.js
Labels: :sparkles: feature

#634 :bug: fix the speaker block overflow in proposal page
  src/screens/organizer/proposal/proposal.css
  src/styles/components/titles.css
Labels: :bug: bug

#636 :bug: avoid proposals reload when checking all
  src/components/form/__snapshots__/renderCheckbox.spec.jsx.snap
  src/components/form/checkbox/__snapshots__/checkbox.spec.jsx.snap
  src/components/form/checkbox/checkbox.jsx
  src/components/list/listItem.jsx
  src/screens/organizer/proposals/proposals.reactions.js
  src/screens/organizer/proposals/proposalsList/proposalsList.jsx
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.jsx
Labels: :bug: bug

#574 :sparkles: email.to.all.organisators.by.config
  functions/email/index.js
  functions/email/templates/talkConfirmed.js
  functions/email/templates/talkDeclined.js
  functions/helpers/eventEmails.js
  functions/triggers/onCreateProposal.js
  functions/triggers/onCreateProposal.test.js
  functions/triggers/onUpdateProposal.js
  functions/triggers/onUpdateProposal.test.js
  functions/triggers/onUpdateTalk.js
  scripts/helpers/initFirestore.js
  scripts/helpers/updates.js
  scripts/update-event-emails-notifications.js
  scripts/update-event-users-addresses.js
  src/components/alert/alert.css
  src/components/form/checkbox/checkbox.jsx
  src/screens/organizer/event/edit/cfp/cfp.jsx
  src/screens/organizer/event/edit/deliberation/deliberation.container.js
  src/screens/organizer/event/edit/deliberation/deliberation.jsx
  src/screens/organizer/event/edit/deliberation/deliberation.module.css
  src/screens/organizer/event/edit/eventTabs/eventTabs.css
  src/screens/organizer/event/form/eventForm.jsx
  src/store/listeners.js
Labels: :sparkles: feature

#637 :sparkles: add confirmation popin when sending emails
  package.json
  src/screens/components/addUserModal/addUserModal.jsx
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.container.js
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.jsx
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.messages.js
  yarn.lock
Labels: :sparkles: feature

#639 :recycle: add event settings collection
  config/firestore.rules
  functions/api/middlewares/apiKey.js
  functions/firestore/event.js
  functions/helpers/eventEmails.js
  functions/triggers/onCreateProposal.js
  functions/triggers/onCreateProposal.test.js
  functions/triggers/onUpdateProposal.js
  functions/triggers/onUpdateTalk.js
  scripts/helpers/updates.js
  scripts/update-event-emails-notifications.js
  scripts/update-event-new-settings.js
  src/firebase/events.js
  src/screens/organizer/event/edit/api/api.container.js
  src/screens/organizer/event/edit/api/api.jsx
  src/screens/organizer/event/edit/deliberation/deliberation.container.js
  src/screens/organizer/event/edit/deliberation/deliberation.jsx
  src/screens/organizer/proposal/actions/actions.container.js
  src/screens/organizer/proposal/proposal.container.js
  src/screens/organizer/proposals/proposalsFilters/proposalsFilters.container.js
  src/screens/organizer/proposals/proposalsList/proposalInfo/proposalInfo.container.js
  src/screens/organizer/proposals/proposalsList/proposalsList.container.js
  src/screens/organizer/proposals/proposalsToolbar/proposalsToolbar.container.js
  src/store/listeners.js
  src/store/reactions/events.js
  src/store/reducers/data/index.js
Labels: :recycle: refactoring

#640 :bug: set a default recipients for emails with only bcc
  functions/triggers/onCreateProposal.js
Labels: :bug: bug

#642 :arrow_up: upgrade dependencies
  functions/package.json
  functions/yarn.lock
  package.json
  scripts/package.json
  scripts/yarn.lock
  yarn.lock
Labels: dependencies
