Repository bpetetot/conference-hall, pull requests merged in 2019-03, with the labels that each got.

#493 :bug: fix code style in markdown display
  src/components/markdown/markdown.css
Labels: :bug: bug

#495 :arrow_up: upgrade dependencies k-ramel, react, babel
  package.json
  src/store/store.js
  yarn.lock
Labels: :wrench: technical

#496 :recycle: upgrade lodash and functions dependencies
  functions/package.json
  functions/yarn.lock
  package.json
Labels: :wrench: technical

#505 :recycle: replace auth popup by redirect
  src/screens/conference/login/login.jsx
  src/store/reactions/auth.js
  src/store/reactions/firebase.js
Labels: :construction: WIP

#506 :sparkles: display login error messages
  src/screens/conference/login/authError/authError.container.js
  src/screens/conference/login/authError/authError.jsx
  src/screens/conference/login/authError/index.js
  src/screens/conference/login/login.css
  src/screens/conference/login/login.jsx
Labels: :sparkles: feature

#507 :arrow_up: upgrade react, firebase, final-form
  functions/package.json
  functions/yarn.lock
  package.json
  yarn.lock
Labels: :wrench: technical

#478 :sparkle: cc conference mailing list in rejection, acceptance email
  functions/email/index.js
  functions/triggers/onCreateProposal.js
  functions/triggers/onUpdateProposal.js
  functions/triggers/onUpdateTalk.js
Labels: :sparkles: feature
